name: Build and deploy Python project to Azure Function App - phisingfunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './release.zip' # Set this to the zipped artifact
  PYTHON_VERSION: '3.9' # Python version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into a target folder
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --target="./phishing_function/.python_packages/lib/site-packages" -r phishing_function/requirements.txt

      - name: Zip function app and dependencies for deployment
        run: |
          cd phishing_function
          zip -r ../release.zip . # Zipping the phishing_function directory contents (includes .python_packages)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5DDAB9A1DB214806B0C780A16AB252B3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_701DF401156B46C28EE071BE7E6623D6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_652EED63E28D46459FAB7F0A006818C1 }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'phisingfunction'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
